// https://grimdawn-archive.fandom.com/wiki/Category:Masteries
var skillList = {
	'MarkoviansAdvantage': {title: "Markovian's Advantage", img: 'img/soldier/markovian_s_advantage.png', url: "https://grimdawn.fandom.com/wiki/Markovian's_Advantage_(Skill)"},
	'ZolhansTechnique': {title: "Zolhan's Technique", img: 'img/soldier/zolhan_s_technique.png', url: "https://grimdawn.fandom.com/wiki/Zolhan's_Technique_(Skill)"},
	'WarCry': {title: 'War Cry', img: 'img/soldier/war_cry.png', url: 'https://grimdawn.fandom.com/wiki/War_Cry_(Skill)'},
	'Terrify': {title: 'Terrify', img: 'img/soldier/terrify.png', url: 'https://grimdawn.fandom.com/wiki/Terrify_(Skill)'},
	'BreakMorale': {title: 'Break Morale', img: 'img/soldier/break_morale.png', url: 'https://grimdawn.fandom.com/wiki/Break_Morale_(Skill)'},
	'FightingSpirit': {title: 'Fighting Spirit', img: 'img/soldier/fighting_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Fighting_Spirit_(Skill)'},
	'BladeArc': {title: 'Blade Arc', img: 'img/soldier/blade_arc.png', url: 'https://grimdawn.fandom.com/wiki/Blade_Arc_(Skill)'},
	'CleanSweep': {title: 'Clean Sweep', img: 'img/soldier/clean_sweep.png', url: 'https://grimdawn.fandom.com/wiki/Clean_Sweep_(Skill)'},
	'Laceration': {title: 'Laceration', img: 'img/soldier/laceration.png', url: 'https://grimdawn.fandom.com/wiki/Laceration_(Skill)'},
	'OleronsRage': {title: "Oleron's Rage", img: 'img/soldier/oleron_s_rage.png', url: "https://grimdawn.fandom.com/wiki/Oleron's_Rage_(Skill)"},
	'Forcewave': {title: 'Forcewave', img: 'img/soldier/forcewave.png', url: 'https://grimdawn.fandom.com/wiki/Forcewave_(Skill)'},
	'Tremor': {title: 'Tremor', img: 'img/soldier/tremor.png', url: 'https://grimdawn.fandom.com/wiki/Tremor_(Skill)'},
	'RendingForce': {title: 'Rending Force', img: 'img/soldier/rending_force.png', url: 'https://grimdawn.fandom.com/wiki/Rending_Force_(Skill)'},
	'InternalTrauma': {title: 'Internal Trauma', img: 'img/soldier/internal_trauma.png', url: 'https://grimdawn.fandom.com/wiki/Internal_Trauma_(Skill)'},
	'Blitz': {title: 'Blitz', img: 'img/soldier/blitz.png', url: 'https://grimdawn.fandom.com/wiki/Blitz_(Skill)'},
	'Blindside': {title: 'Blindside', img: 'img/soldier/blindside.png', url: 'https://grimdawn.fandom.com/wiki/Blindside_(Skill)'},
	'CounterStrike': {title: 'Counter Strike', img: 'img/soldier/counter_strike.png', url: 'https://grimdawn.fandom.com/wiki/Counter_Strike_(Skill)'},
	'Cadence': {title: 'Cadence', img: 'img/soldier/cadence.png', url: 'https://grimdawn.fandom.com/wiki/Cadence_(Skill)'},
	'Discord': {title: 'Discord', img: 'img/soldier/discord.png', url: 'https://grimdawn.fandom.com/wiki/Discord_(Skill)'},
	'FightingForm': {title: 'Fighting Form', img: 'img/soldier/fighting_form.png', url: 'https://grimdawn.fandom.com/wiki/Fighting_Form_(Skill)'},
	'DeadlyMomentum': {title: 'Deadly Momentum', img: 'img/soldier/deadly_momentum.png', url: 'https://grimdawn.fandom.com/wiki/Deadly_Momentum_(Skill)'},
	'MenhirsWill': {title: "Menhir's Will", img: 'img/soldier/menhir_s_will.png', url: "https://grimdawn.fandom.com/wiki/Menhir's Will_(Skill)"},
	'Overguard': {title: 'Overguard', img: 'img/soldier/overguard.png', url: 'https://grimdawn.fandom.com/wiki/Overguard_(Skill)'},
	'FieldCommand': {title: 'Field Command', img: 'img/soldier/field_command.png', url: 'https://grimdawn.fandom.com/wiki/Field_Command_(Skill)'},	
	'SquadTactics': {title: 'Squad Tactics', img: 'img/soldier/squad_tactics.png', url: 'https://grimdawn.fandom.com/wiki/Squad_Tactics_(Skill)'},
	'MenhirsBulwark': {title: "Menhir's Bulwark", img: 'img/soldier/menhir_s_bulwark.png', url: "https://grimdawn.fandom.com/wiki/Menhir's_Bulwark_(Skill)"},
	'MilitaryConditioning': {title: 'Military Conditioning', img: 'img/soldier/military_conditioning.png', url: 'https://grimdawn.fandom.com/wiki/Military_Conditioning_(Skill)'},
	'ShieldTraining': {title: 'Shield Training', img: 'img/soldier/shield_training.png', url: 'https://grimdawn.fandom.com/wiki/Shield_Training_(Skill)'},
	'Veterancy': {title: 'Veterancy', img: 'img/soldier/veterancy.png', url: 'https://grimdawn.fandom.com/wiki/Veterancy_(Skill)'},
	'DecoratedSoldier': {title: 'Decorated Soldier', img: 'img/soldier/decorated_soldier.png', url: 'https://grimdawn.fandom.com/wiki/Decorated_Soldier_(Skill)'},
	'ScarsofBattle': {title: 'Scars of Battle', img: 'img/soldier/scars_of_battle.png', url: 'https://grimdawn.fandom.com/wiki/Scars_of_Battle_(Skill)'},

	'FlameTouched': {title: 'Flame Touched', img: 'img/demolitionist/flame_touched.png', url: 'https://grimdawn.fandom.com/wiki/Flame_Touched_(Skill)'},
	'Temper': {title: 'Temper', img: 'img/demolitionist/temper.png', url: 'https://grimdawn.fandom.com/wiki/Temper_(Skill)'},
	'BlastShield': {title: 'Blast Shield', img: 'img/demolitionist/blast_shield.png', url: 'https://grimdawn.fandom.com/wiki/Blast_Shield_(Skill)'},
	'FireStrike': {title: 'Fire Strike', img: 'img/demolitionist/fire_strike.png', url: 'https://grimdawn.fandom.com/wiki/Fire_Strike_(Skill)'},
	'ExplosiveStrike': {title: 'Explosive Strike', img: 'img/demolitionist/explosive_strike.png', url: 'https://grimdawn.fandom.com/wiki/Explosive_Strike_(Skill)'},
	'SearingMight': {title: 'Searing Might', img: 'img/demolitionist/searing_might.png', url: 'https://grimdawn.fandom.com/wiki/Searing_Might_(Skill)'},
	'SearingStrike': {title: 'Searing Strike', img: 'img/demolitionist/searing_strike.png', url: 'https://grimdawn.fandom.com/wiki/Searing_Strike_(Skill)'},
	'StaticStrike': {title: 'Static Strike', img: 'img/demolitionist/static_strike.png', url: 'https://grimdawn.fandom.com/wiki/Static_Strike_(Skill)'},
	'Brimstone': {title: 'Brimstone', img: 'img/demolitionist/brimstone.png', url: 'https://grimdawn.fandom.com/wiki/Brimstone_(Skill)'},
	'BlackwaterCocktail': {title: 'Blackwater Cocktail', img: 'img/demolitionist/blackwater_cocktail.png', url: 'https://grimdawn.fandom.com/wiki/Blackwater_Cocktail_(Skill)'},
	'HighPotency': {title: 'High Potency', img: 'img/demolitionist/high_potency.png', url: 'https://grimdawn.fandom.com/wiki/High_Potency_(Skill)'},
	'DemonFire': {title: 'Demon Fire', img: 'img/demolitionist/demon_fire.png', url: 'https://grimdawn.fandom.com/wiki/Demon_Fire_(Skill)'},
	'AgonizingFlames': {title: 'Agonizing Flames', img: 'img/demolitionist/agonizing_flames.png', url: 'https://grimdawn.fandom.com/wiki/Agonizing_Flames_(Skill)'},
	'StunJacks': {title: 'Stun Jacks', img: 'img/demolitionist/stun_jacks.png', url: 'https://grimdawn.fandom.com/wiki/Stun_Jacks_(Skill)'},
	'QuickJacks': {title: 'Quick Jacks', img: 'img/demolitionist/quick_jacks.png', url: 'https://grimdawn.fandom.com/wiki/Quick_Jacks_(Skill)'},
	'FullSpread': {title: 'Full Spread', img: 'img/demolitionist/full_spread.png', url: 'https://grimdawn.fandom.com/wiki/Full_Spread_(Skill)'},
	'ThermiteMine': {title: 'Thermite Mine', img: 'img/demolitionist/thermite_mine.png', url: 'https://grimdawn.fandom.com/wiki/Thermite_Mine_(Skill)'},
	'HellfireMine': {title: 'Hellfire Mine', img: 'img/demolitionist/hellfire_mine.png', url: 'https://grimdawn.fandom.com/wiki/Hellfire_Mine_(Skill)'},
	'CanisterBomb': {title: 'Canister Bomb', img: 'img/demolitionist/canister_bomb.png', url: 'https://grimdawn.fandom.com/wiki/Canister_Bomb_(Skill)'},
	'ConcussiveBomb': {title: 'Concussive Bomb', img: 'img/demolitionist/concussive_bomb.png', url: 'https://grimdawn.fandom.com/wiki/Concussive_Bomb_(Skill)'},
	'ImprovedCasing': {title: 'Improved Casing', img: 'img/demolitionist/improved_casing.png', url: 'https://grimdawn.fandom.com/wiki/Improved_Casing_(Skill)'},
	'UlzuinsChosen': {title: "Ulzuin's Chosen", img: 'img/demolitionist/ulzuin_s_chosen.png', url: "https://grimdawn.fandom.com/wiki/Ulzuin's_Chosen_(Skill)"},
	'Flashbang': {title: 'Flashbang', img: 'img/demolitionist/flashbang.png', url: 'https://grimdawn.fandom.com/wiki/Flashbang_(Skill)'},
	'SearingLight': {title: 'Searing Light', img: 'img/demolitionist/searing_light.png', url: 'https://grimdawn.fandom.com/wiki/Searing_Light_(Skill)'},
	'Grenado': {title: 'Grenado', img: 'img/demolitionist/grenado.png', url: 'https://grimdawn.fandom.com/wiki/Grenado_(Skill)'},
	'HighImpact': {title: 'High Impact', img: 'img/demolitionist/high_impact.png', url: 'https://grimdawn.fandom.com/wiki/High_Impact_(Skill)'},
	'SkyfireGrenado': {title: 'Skyfire Grenado', img: 'img/demolitionist/skyfire_grenado.png', url: 'https://grimdawn.fandom.com/wiki/Skyfire_Grenado_(Skill)'},
	'VindictiveFlame': {title: 'Vindictive Flame', img: 'img/demolitionist/vindictive_flame.png', url: 'https://grimdawn.fandom.com/wiki/Vindictive_Flame_(Skill)'},
	'UlzuinsWrath': {title: "Ulzuin's Wrath", img: 'img/demolitionist/ulzuin_s_wrath.png', url: "https://grimdawn.fandom.com/wiki/Ulzuin's_Wrath_(Skill)"},
	'MortarTrap': {title: "Mortar Trap", img: 'img/demolitionist/mortar_trap.png', url: "https://grimdawn.fandom.com/wiki/Mortar_Trap_(Skill)"},
	'HeavyOrdinance': {title: "Heavy Ordinance", img: 'img/demolitionist/heavy_ordinance.png', url: "https://grimdawn.fandom.com/wiki/Heavy_Ordinance_(Skill)"},
	'TheBigOne': {title: "The Big One", img: 'img/demolitionist/the_big_one.png', url: "https://grimdawn.fandom.com/wiki/The_Big_One_(Skill)"},

	'SigilofConsumption': {title: 'Sigil of Consumption', img: 'img/occultist/sigil_of_consumption.png', url: 'https://grimdawn.fandom.com/wiki/Sigil_of_Consumption_(Skill)'},
	'Destruction': {title: 'Destruction', img: 'img/occultist/destruction.png', url: 'https://grimdawn.fandom.com/wiki/Destruction_(Skill)'},
	'DoomBolt': {title: 'Doom Bolt', img: 'img/occultist/doom_bolt.png', url: 'https://grimdawn.fandom.com/wiki/Doom_Bolt_(Skill)'},
	'SolaelsWitchfire': {title: 'Solael’s Witchfire', img: 'img/occultist/solael_s_witchfire.png', url: "https://grimdawn.fandom.com/wiki/Solael's_Witchfire_(Skill)"},
	'ConsecratedBlade': {title: 'Consecrated Blade', img: 'img/occultist/consecrated_blade.png', url: 'https://grimdawn.fandom.com/wiki/Consecrated_Blade_(Skill)'},
	'SecondRite': {title: 'Second Rite', img: 'img/occultist/second_rite.png', url: 'https://grimdawn.fandom.com/wiki/Second_Rite_(Skill)'},
	'Possession': {title: 'Possession', img: 'img/occultist/possession.png', url: 'https://grimdawn.fandom.com/wiki/Possession_(Skill)'},
	'DreegsEvilEye': {title: "Dreeg's Evil Eye", img: 'img/occultist/dreeg_s_evil_eye.png', url: "https://grimdawn.fandom.com/wiki/Dreeg's_Evil_Eye_(Skill)"},
	'BloodBurst': {titile: 'Blood Burst', img: 'img/occultist/blood_burst.png', url: 'https://grimdawn.fandom.com/wiki/Blood_Burst_(Skill)'},
	'FocusedGaze': {title: 'Focused Gaze', img: 'img/occultist/focused_gaze.png', url: 'https://grimdawn.fandom.com/wiki/Focused_Gaze_(Skill)'},
	'TerrifyingGaze': {title: 'Terrifying Gaze', img: 'img/occultist/terrifying_gaze.png', url: 'https://grimdawn.fandom.com/wiki/Terrifying_Gaze_(Skill)'},
	'VileEruption': {title: 'Vile Eruption', img: 'img/occultist/vile_eruption.png', url: 'https://grimdawn.fandom.com/wiki/Vile_Eruption_(Skill)'},
	'BloodyPox': {title: 'Bloody Pox', img: 'img/occultist/bloody_pox.png', url: 'https://grimdawn.fandom.com/wiki/Bloody_Pox_(Skill)'},
	'FeveredRage': {title: 'Fevered Rage', img: 'img/occultist/fevered_rage.png', url: 'https://grimdawn.fandom.com/wiki/Fevered_Rage_(Skill)'},
	'Wasting': {title: 'Wasting', img: 'img/occultist/wasting.png', url: 'https://grimdawn.fandom.com/wiki/Wasting_(Skill)'},
	'BlackDeath': {title: 'Black Death', img: 'img/occultist/black_death.png', url: 'https://grimdawn.fandom.com/wiki/Black_Death_(Skill)'},
	'CurseofFrailty': {title: 'Curse of Frailty', img: 'img/occultist/curse_of_frailty.png', url: 'https://grimdawn.fandom.com/wiki/Curse_of_Frailty_(Skill)'},
	'Vulnerability': {title: 'Vulnerability', img: 'img/occultist/vulnerability.png', url: 'https://grimdawn.fandom.com/wiki/Vulnerability_(Skill)'},
	'BloodofDreeg': {title: 'Blood of Dreeg', img: 'img/occultist/blood_of_dreeg.png', url: 'https://grimdawn.fandom.com/wiki/Blood_of_Dreeg_(Skill)'},
	'AspectoftheGuardian': {title: 'Aspect of Guardian', img: 'img/occultist/aspect_of_guardian.png', url: 'https://grimdawn.fandom.com/wiki/Aspect_of_the_Guardian_(Skill)'},
	'SummonFamiliar': {title: 'Summon Familiar', img: 'img/occultist/summon_familiar.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Familiar_(Skill)'},
	'MendFlesh': {title: 'Mend Flesh', img: 'img/occultist/mend_flesh.png', url: 'https://grimdawn.fandom.com/wiki/Mend_Flesh_(Skill)'},
	'StormSpirit': {title: 'Storm Spirit', img: 'img/occultist/storm_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Spirit_(Skill)'},
	'LightningStrike': {title: 'Lightning Strike', img: 'img/occultist/lightning_strike.png', url: 'https://grimdawn.fandom.com/wiki/Lightning_Strike_(Skill)'},
	'BondsofBysmiel': {title: 'Bonds of Bysmiel', img: 'img/occultist/bonds_of_bysmiel.png', url: 'https://grimdawn.fandom.com/wiki/Bonds_of_Bysmiel_(Skill)'},
	'Manipulation': {title: 'Manipulation', img: 'img/occultist/manipulation.png', url: 'https://grimdawn.fandom.com/wiki/Manipulation_(Skill)'},
	'SummonHellhound': {title: 'Summon Hellhound', img: 'img/occultist/summon_hellhound.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Hellhound_(Skill)'},
	'EmberClaw': {title: 'Ember Claw', img: 'img/occultist/ember_claw.png', url: 'https://grimdawn.fandom.com/wiki/Ember_Claw_(Skill)'},
	'Hellfire': {title: 'Hellfire', img: 'img/occultist/hellfire.png', url: 'https://grimdawn.fandom.com/wiki/Hellfire_(Skill)'},
	'InfernalBreath': {title: 'Infernal Breath', img: 'img/occultist/infernal_breath.png', url: 'https://grimdawn.fandom.com/wiki/Infernal_Breath_(Skill)'},

	'DualBlades': {title: 'Dual Blades', img: 'img/nightblade/dual_blades.png', url: 'https://grimdawn.fandom.com/wiki/Dual_Blades_(Skill)'},
	'BelgothiansShears': {title: "Belgothian's Shears", img: 'img/nightblade/belgothian_s_shears.png', url: "https://grimdawn.fandom.com/wiki/Belgothian's_Shears_(Skill)"},
	'NidallasHiddenHand': {title: "Nidalla's Hidden Hand", img: 'img/nightblade/nidalla_s_hidden_hand.png', url: "https://grimdawn.fandom.com/wiki/Nidalla's_Hidden_Hand_(Skill)"},
	'AmarastasQuickCut': {title: "Amarasta's Quick Cut", img: 'img/nightblade/amarasta_s_quick_cut.png', url: "https://grimdawn.fandom.com/wiki/Amarasta's_Quick_Cut_(Skill)"},
	'WhirlingDeath': {title: 'Whirling Death', img: 'img/nightblade/whirling_death.png', url: 'https://grimdawn.fandom.com/wiki/Whirling_Death_(Skill)'},
	'Execution': {title: 'Execution', img: 'img/nightblade/execution.png', url: 'https://grimdawn.fandom.com/wiki/Execution_(Skill)'},
	'PhantasmalBlades': {title: 'Phantasmal Blades', img: 'img/nightblade/phantasmal_blades.png', url: 'https://grimdawn.fandom.com/wiki/Phantasmal_Blades_(Skill)'},
	'FreneticThrow': {title: 'Frenetic Throw', img: 'img/nightblade/frenetic_throw.png', url: 'https://grimdawn.fandom.com/wiki/Frenetic_Throw_(Skill)'},
	'HeartSeeker': {title: 'Heart Seeker', img: 'img/nightblade/heart_seeker.png', url: 'https://grimdawn.fandom.com/wiki/Heart_Seeker_(Skill)'},
	'NetherEdge': {title: 'Nether Edge', img: 'img/nightblade/nether_edge.png', url: 'https://grimdawn.fandom.com/wiki/Nether_Edge_(Skill)'},
	'BladeSpirit': {title: 'Blade Spirit', img: 'img/nightblade/blade_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Blade_Spirit_(Skill)'},
	'AmarastasBladeBurst': {title: "Amarasta's Blade Burst", img: 'img/nightblade/amarasta_s_blade_burst.png', url: "https://grimdawn.fandom.com/wiki/Amarasta's_Blade_Burst_(Skill)"},
	'LethalAssault': {title: 'Lethal Assault', img: 'img/nightblade/lethal_assault.png', url: 'https://grimdawn.fandom.com/wiki/Lethal_Assault_(Skill)'},
	'RingofSteel': {title: 'Ring of Steel', img: 'img/nightblade/ring_of_steel.png', url: 'https://grimdawn.fandom.com/wiki/Ring_of_Steel_(Skill)'},
	'RingofFrost': {title: 'Ring of Frost', img: 'img/nightblade/ring_of_frost.png', url: 'https://grimdawn.fandom.com/wiki/Ring_of_Frost_(Skill)'},
	'CircleofSlaughter': {title: 'Circle of Slaughter', img: 'img/nightblade/circle_of_slaughter.png', url: 'https://grimdawn.fandom.com/wiki/Circle_of_Slaughter_(Skill)'},
	'ShadowStrike': {title: 'Shadow Strike', img: 'img/nightblade/shadow_strike.png', url: 'https://grimdawn.fandom.com/wiki/Shadow_Strike_(Skill)'},
	'NidallasJustifiableEnds': {title: "Nidalla's Justifiable Ends", img: 'img/nightblade/nidalla_s_justifiable_ends.png', url: "https://grimdawn.fandom.com/wiki/Nidalla's_Justifiable_Ends_(Skill)"},
	'Nightfall': {title: 'Nighfall', img: 'img/nightblade/nightfall.png', url: 'https://grimdawn.fandom.com/wiki/Nightfall_(Skill)'},
	'PneumaticBurst': {title: 'Pneumatic Burst', img: 'img/nightblade/pneumatic_burst.png', url: 'https://grimdawn.fandom.com/wiki/Pneumatic_Burst_(Skill)'},
	'BreathofBelgothian': {title: 'Breath of Belgothian', img: 'img/nightblade/breath_of_belgothian.png', url: 'https://grimdawn.fandom.com/wiki/Breath_of_Belgothian_(Skill)'},
	'ShadowDance': {title: 'Shadow Dance', img: 'img/nightblade/shadow_dance.png', url: 'https://grimdawn.fandom.com/wiki/Shadow_Dance_(Skill)'},
	'ElementalAwakening': {title: 'Elemental Awakening', img: 'img/nightblade/elemental_awakening.png', url: 'https://grimdawn.fandom.com/wiki/Elemental_Awakening_(Skill)'},
	'VeilofShadow': {title: 'Veil of Shadow', img: 'img/nightblade/veil_of_shadow.png', url: 'https://grimdawn.fandom.com/wiki/Veil_of_Shadow_(Skill)'},
	'NightsChill': {title: "Night's Chill", img: 'img/nightblade/night_s_chill.png', url: "https://grimdawn.fandom.com/wiki/Night's_Chill_(Skill)"},
	'BladeBarrier': {title: 'Blade Barrier', img: 'img/nightblade/blade_barrier.png', url: 'https://grimdawn.fandom.com/wiki/Blade_Barrier_(Skill)'},
	'BladeTrap': {title: 'Blade Trap', img: 'img/nightblade/blade_trap.png', url: 'https://grimdawn.fandom.com/wiki/Blade_Trap_(Skill)'},
	'DevouringBlades': {title: 'Devouring Blades', img: 'img/nightblade/devouring_blades.png', url: 'https://grimdawn.fandom.com/wiki/Devouring_Blades_(Skill)'},	
	'PhantasmalArmor': {title: 'Phantasmal Armor', img: 'img/nightblade/phantasmal_armor.png', url: 'https://grimdawn.fandom.com/wiki/Phantasmal_Armor_(Skill)'},
	'AnatomyofMurder': {title: 'Anatomy of Murder', img: 'img/nightblade/anatomy_of_murder.png', url: 'https://grimdawn.fandom.com/wiki/Anatomy_of_Murder_(Skill)'},
	'MercilessRepertoire': {title: 'Merciless Repertoire', img: 'img/nightblade/merciless_repertoire.png', url: 'https://grimdawn.fandom.com/wiki/Merciless_Repertoire_(Skill)'},

	'IskandrasElementalExchange': {title: "Iskandra's Elemental Exchange", img: 'img/arcanist/iskandra_s_elemental_exchange.png', url: "https://grimdawn.fandom.com/wiki/Iskandra's_Elemental_Exchange_(Skill)"},
	'Manifestation': {title: 'Manifestation', img: 'img/arcanist/manifestation.png', url: 'https://grimdawn.fandom.com/wiki/Manifestation_(Skill)'},
	'Overload': {title: 'Overload', img: 'img/arcanist/overload.png', url: 'https://grimdawn.fandom.com/wiki/Overload_(Skill)'},
	'ElementalBalance': {title: 'Elemental Balance', img: 'img/arcanist/elemental_balance.png', url: 'https://grimdawn.fandom.com/wiki/Elemental_Balance_(Skill)'},
	'MirrorofEreoctes': {title: 'Mirror of Ereoctes', img: 'img/arcanist/mirror_of_ereoctes.png', url: 'https://grimdawn.fandom.com/wiki/Mirror_of_Ereoctes_(Skill)'},
	'MaivensSphereofProtection': {title: "Maiven's Sphere of Protection", img: 'img/arcanist/maiven_s_sphere_of_protection.png', url: "https://grimdawn.fandom.com/wiki/Maiven's_Sphere_of_Protection_(Skill)"},
	'Conversion': {title: 'Conversion', img: 'img/arcanist/conversion.png', url: 'https://grimdawn.fandom.com/wiki/Conversion_(Skill)'},
	'RecklessPower': {title: 'Reckless Power', img: 'img/arcanist/reckless_power.png', url: 'https://grimdawn.fandom.com/wiki/Reckless_Power_(Skill)'},
	'CallidorsTempest': {title: "Callidor's Tempest", img: 'img/arcanist/callidor_s_tempest.png', url: "https://grimdawn.fandom.com/wiki/Callidor's_Tempest_(Skill)"},
	'WrathofAgrivix': {title: 'Wrath of Agrivix', img: 'img/arcanist/wrath_of_agrivix.png', url: 'https://grimdawn.fandom.com/wiki/Wrath_of_Agrivix_(Skill)'},
	'Inferno': {title: 'Inferno', img: 'img/arcanist/inferno.png', url: 'https://grimdawn.fandom.com/wiki/Inferno_(Skill)'},
	'PanettisReplicatingMissile': {title: "Panetti's Replicating Missile", img: 'img/arcanist/panetti_s_replicating_missile.png', url: "https://grimdawn.fandom.com/wiki/Panetti's_Replicating_Missile_(Skill)"},
	'Distortion': {title: 'Distortion', img: 'img/arcanist/distortion.png', url: 'https://grimdawn.fandom.com/wiki/Distortion_(Skill)'},
	'Supercharged': {title: 'Supercharged', img: 'img/arcanist/supercharged.png', url: 'https://grimdawn.fandom.com/wiki/Supercharged_(Skill)'},
	'Proliferation': {title: 'Proliferation', img: 'img/arcanist/proliferation.png', url: 'https://grimdawn.fandom.com/wiki/Proliferation_(Skill)'},
	'Devastation': {title: 'Devastation', img: 'img/arcanist/devastation.png', url: 'https://grimdawn.fandom.com/wiki/Devastation_(Skill)'},
	'OlecrasFlashFreeze': {title: "Olecra's Flash Freeze", img: 'img/arcanist/olexra_s_flash_freeze.png', url: "https://grimdawn.fandom.com/wiki/Olecra's_Flash_Freeze_(Skill)"},
	'AbsoluteZero': {title: 'Absolute Zero', img: 'img/arcanist/absolute_zero.png', url: 'https://grimdawn.fandom.com/wiki/Absolute_Zero_(Skill)'},
	'AlbrechtsAetherRay': {title: "Albrecht's Aether Ray", img: 'img/arcanist/albrecht_s_aether_ray.png', url: "https://grimdawn.fandom.com/wiki/Albrecht's_Aether_Ray_(Skill)"},
	'TaintedPower': {title: 'Tainted Power', img: 'img/arcanist/tainted_power.png', url: 'https://grimdawn.fandom.com/wiki/Tainted_Power_(Skill)'},
	'Disintegration': {title: 'Disintegration', img: 'img/arcanist/disintegration.png', url: 'https://grimdawn.fandom.com/wiki/Disintegration_(Skill)'},
	'TrozansSkyShard': {title: "Trozan's Sky Shard", img: 'img/arcanist/trozan_s_sky_shard.png', url: "https://grimdawn.fandom.com/wiki/Trozan's_Sky_Shard_(Skill)"},
	'FrozenCore': {title: 'Frozen Core', img: 'img/arcanist/frozen_core.png', url: 'https://grimdawn.fandom.com/wiki/Frozen_Core_(Skill)'},
	'ShatteredStar': {title: 'Shattered Star', img: 'img/arcanist/shattered_star.png', url: 'https://grimdawn.fandom.com/wiki/Shattered_Star_(Skill)'},
	'StarPact': {title: 'Star Pact', img: 'img/arcanist/star_pact.png', url: 'https://grimdawn.fandom.com/wiki/Star_Pact_(Skill)'},
	'InnerFocus': {title: 'Inner Focus', img: 'img/arcanist/inner_focus.png', url: 'https://grimdawn.fandom.com/wiki/Inner_Focus_(Skill)'},
	'ArcaneWill': {title: 'Arcane Will', img: 'img/arcanist/arcane_will.png', url: 'https://grimdawn.fandom.com/wiki/Arcane_Will_(Skill)'},
	'Nullification': {title: 'Nullification', img: 'img/arcanist/nullification.png', url: 'https://grimdawn.fandom.com/wiki/Nullification_(Skill)'},
	'MentalAlacrity': {title: 'Mental Alacrity', img: 'img/arcanist/mental_alacrity.png', url: 'https://grimdawn.fandom.com/wiki/Mental_Alacrity_(Skill)'},
	'FabricofReality': {title: 'Fabric of Reality', img: 'img/arcanist/fabric_of_reality.png', url: 'https://grimdawn.fandom.com/wiki/Fabric_of_Reality_(Skill)'},

	'BruteForce': {title: 'Brute Force', img: 'img/shaman/brute_force.png', url: 'https://grimdawn.fandom.com/wiki/Brute_Force_(Skill)'},
	'FeralHunger': {title: 'Feral Hunger', img: 'img/shaman/feral_hunger.png', url: 'https://grimdawn.fandom.com/wiki/Feral_Hunger_(Skill)'},
	'Upheaval': {title: 'Upheaval', img: 'img/shaman/upheaval.png', url: 'https://grimdawn.fandom.com/wiki/Upheaval_(Skill)'},
	'WendigoTotem': {title: 'Wendigo Totem', img: 'img/shaman/wendigo_totem.png', url: 'https://grimdawn.fandom.com/wiki/Wendigo_Totem_(Skill)'},
	'BloodPact': {title: 'Blood Pact', img: 'img/shaman/blood_pact.png', url: 'https://grimdawn.fandom.com/wiki/Blood_Pact_(Skill)'},
	'PrimalStrike': {title: 'Primal Strike', img: 'img/shaman/primal_strike.png', url: 'https://grimdawn.fandom.com/wiki/Primal_Strike_(Skill)'},	
	'ThunderousStrike': {title: 'Thunderous Strike', img: 'img/shaman/thunderous_strike.png', url: 'https://grimdawn.fandom.com/wiki/Thunderous_Strike_(Skill)'},	
	'Torrent': {title: 'Torrent', img: 'img/shaman/torrent.png', url: 'https://grimdawn.fandom.com/wiki/Torrent_(Skill)'},	
	'StormSurge': {title: 'Storm Surge', img: 'img/shaman/storm_surge.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Surge_(Skill)'},	
	'StormTotem': {title: 'Storm Totem ', img: 'img/shaman/storm_totem.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Totem_(Skill)'},
	'CorruptedStorm': {title: 'Corrupted Storm', img: 'img/shaman/corrupted_storm.png', url: 'https://grimdawn.fandom.com/wiki/Corrupted_Storm_(Skill)'},
	'StormcallersPact': {title: "Stormcaller's Pact", img: 'img/shaman/stormcaller_s_pact.png', url: "https://grimdawn.fandom.com/wiki/Stormcaller's_Pact_(Skill)"},	
	'Savagery': {title: 'Savagery', img: 'img/shaman/savagery.png', url: 'https://grimdawn.fandom.com/wiki/Savagery_(Skill)'},
	'MightoftheBear': {title: 'Might of the Bear', img: 'img/shaman/might_of_the_bear.png', url: 'https://grimdawn.fandom.com/wiki/Might_of_the_Bear_(Skill)'},
	'TenacityoftheBoar': {title: 'Tenacity of the Boar', img: 'img/shaman/tenacity_of_the_boar.png', url: 'https://grimdawn.fandom.com/wiki/Tenacity_of_the_Boar_(Skill)'},
	'StormTouched': {title: 'Storm Touched', img: 'img/shaman/storm_touched.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Touched_(Skill)'},
	'WindDevil': {title: 'Wind Devil', img: 'img/shaman/wind_devil.png', url: 'https://grimdawn.fandom.com/wiki/Wind_Devil_(Skill)'},
	'RagingTempest': {title: 'Raging Tempest', img: 'img/shaman/raging_tempest.png', url: 'https://grimdawn.fandom.com/wiki/Raging_Tempest_(Skill)'},
	'Maelstrom': {title: 'Maelstrom', img: 'img/shaman/maelstrom.png', url: 'https://grimdawn.fandom.com/wiki/Maelstrom_(Skill)'},
	'DevouringSwarm': {title: 'Devouring Swarm', img: 'img/shaman/devouring_swarm.png', url: 'https://grimdawn.fandom.com/wiki/Devouring_Swarm_(Skill)'},
	'GraspingVines': {title: 'Grasping Vines', img: 'img/shaman/grasping_vines.png', url: 'https://grimdawn.fandom.com/wiki/Grasping_Vines_(Skill)'},
	'EntanglingVines': {title: 'Entangling Vines', img: 'img/shaman/entangling_vines.png', url: 'https://grimdawn.fandom.com/wiki/Entangling_Vines_(Skill)'},
	'ConjurePrimalSpirit': {title: 'Conjure Primal Spirit', img: 'img/shaman/conjure_primal_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Conjure_Primal_Spirit_(Skill)'},
	'SummonBriarthorn': {title: 'Summon Briarthorn', img: 'img/shaman/summon_briarthorn.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Briarthorn_(Skill)'},
	'GroundSlam': {title: 'Ground Slam', img: 'img/shaman/ground_slam.png', url: 'https://grimdawn.fandom.com/wiki/Ground_Slam_(Skill)'},
	'EmboldeningPresence': {title: 'Emboldening Presence', img: 'img/shaman/emboldening_presence.png', url: 'https://grimdawn.fandom.com/wiki/Emboldening_Presence_(Skill)'},
	'PrimalBond': {title: 'Primal Bond', img: 'img/shaman/primal_bond.png', url: 'https://grimdawn.fandom.com/wiki/Primal_Bond_(Skill)'},
	'MogdrogensPact': {title: 'Mogdrogen’s Pact', img: 'img/shaman/mogdrogen_s_pact.png', url: "https://grimdawn.fandom.com/wiki/Mogdrogen's_Pact_(Skill)"},
	'HeartoftheWild': {title: 'Heart of the Wild', img: 'img/shaman/heart_of_the_wild.png', url: 'https://grimdawn.fandom.com/wiki/Heart_of_the_Wild_(Skill)'},
	'OakSkin': {title: 'Oak Skin', img: 'img/shaman/oak_skin.png', url: 'https://grimdawn.fandom.com/wiki/Oak_Skin_(Skill)'},

	'RangedExpertise': {title: 'Ranged Expertise', img: 'img/inquisitor/ranged_expertise.png', url: 'https://grimdawn.fandom.com/wiki/Ranged_Expertise_(Skill)'},
	'BurstingRound': {title: 'Bursting Round', img: 'img/inquisitor/bursting_round.png', url: 'https://grimdawn.fandom.com/wiki/Bursting_Round_(Skill)'},
	'ChillingRounds': {title: 'Chilling Rounds', img: 'img/inquisitor/chilling_rounds.png', url: 'https://grimdawn.fandom.com/wiki/Chilling_Rounds_(Skill)'},
	'StormSpread': {title: 'Storm Spread', img: 'img/inquisitor/storm_spread.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Spread_(Skill)'},
	'WordofRenewal': {title: 'Word of Renewal', img: 'img/inquisitor/word_of_renewal.png', url: 'https://grimdawn.fandom.com/wiki/Word_of_Renewal_(Skill)'},
	'WordofArms': {title: 'Word of Arms', img: 'img/inquisitor/word_of_arms.png', url: 'https://grimdawn.fandom.com/wiki/Word_of_Arms_(Skill)'},
	'Vigor': {title: 'Vigor', img: 'img/inquisitor/vigor.png', url: 'https://grimdawn.fandom.com/wiki/Vigor_(Skill)'},
	'SteelResolve': {title: 'Steel Resolve', img: 'img/inquisitor/steel_resolve.png', url: 'https://grimdawn.fandom.com/wiki/Steel_Resolve_(Skill)'},
	'AuraofConviction': {title: 'Aura of Conviction', img: 'img/inquisitor/aura_of_conviction.png', url: 'https://grimdawn.fandom.com/wiki/Aura_of_Conviction_(Skill)'},
	'WordofPain': {title: 'Word of Pain', img: 'img/inquisitor/word_of_pain.png', url: 'https://grimdawn.fandom.com/wiki/Word_of_Pain_(Skill)'},
	'WordofAgony': {title: 'Word of Agony', img: 'img/inquisitor/word_of_agony.png', url: 'https://grimdawn.fandom.com/wiki/Word_of_Agony_(Skill)'},
	'DeathSentence': {title: 'Death Sentence', img: 'img/inquisitor/death_sentence.png', url: 'https://grimdawn.fandom.com/wiki/Death_Sentence_(Skill)'},
	'HornofGandarr': {title: 'Horn of Gandarr', img: 'img/inquisitor/horn_of_gandarr.png', url: 'https://grimdawn.fandom.com/wiki/Horn_of_Gandarr_(Skill)'},
	'FlamesofIgnaffar': {title: 'Flames of Ignaffar', img: 'img/inquisitor/flames_of_ignaffar.png', url: 'https://grimdawn.fandom.com/wiki/Flames_of_Ignaffar_(Skill)'},
	'TaintedFlame': {title: 'Tainted Flame', img: 'img/inquisitor/tainted_flame.png', url: 'https://grimdawn.fandom.com/wiki/Tainted_Flame_(Skill)'},
	'Intensify': {title: 'Intensify', img: 'img/inquisitor/intensify.png', url: 'https://grimdawn.fandom.com/wiki/Intensify_(Skill)'},
	'InfernalPurge': {title: 'Infernal Purge', img: 'img/inquisitor/infernal_purge.png', url: 'https://grimdawn.fandom.com/wiki/Infernal_Purge_(Skill)'},
	'EndlessFlame': {title: 'Endless Flame', img: 'img/inquisitor/endless_flame.png', url: 'https://grimdawn.fandom.com/wiki/Endless_Flame_(Skill)'},
	'RuneofHagarrad': {title: 'Rune of Hagarrad', img: 'img/inquisitor/rune_of_hagarrad.png', url: 'https://grimdawn.fandom.com/wiki/Rune_of_Hagarrad_(Skill)'},
	'BitingCold': {title: 'Biting Cold', img: 'img/inquisitor/biting_cold.png', url: 'https://grimdawn.fandom.com/wiki/Biting_Cold_(Skill)'},
	'Chillsurge': {title: 'Chillsurge', img: 'img/inquisitor/chillsurge.png', url: 'https://grimdawn.fandom.com/wiki/Chillsurge_(Skill)'},
	'AuraofCensure': {title: 'Aura of Censure', img: 'img/inquisitor/aura_of_censure.png', url: 'https://grimdawn.fandom.com/wiki/Aura_of_Censure_(Skill)'},
	'StormBoxofElgoloth': {title: 'Storm Box of Elgoloth', img: 'img/inquisitor/storm_box_of_elgoloth.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Box_of_Elgoloth_(Skill)'},
	'AllagastsArcaneNet': {title: "Allagast's Arcane Net", img: 'img/inquisitor/allagast_s_arcane_net.png', url: "https://grimdawn.fandom.com/wiki/Allagast's_Arcane_Net_(Skill)"},
	'LightningTether': {title: 'Lightning Tether', img: 'img/inquisitor/lightning_tether.png', url: 'https://grimdawn.fandom.com/wiki/Lightning_Tether_(Skill)'},
	'InquisitorSeal': {title: 'Inquisitor Seal', img: 'img/inquisitor/inquisitor_seal.png', url: 'https://grimdawn.fandom.com/wiki/Inquisitor_Seal_(Skill)'},
	'NullField': {title: 'Null Field', img: 'img/inquisitor/null_field.png', url: 'https://grimdawn.fandom.com/wiki/Null_Field_(Skill)'},
	'ArcaneEmpowerment': {title: 'Arcane Empowerment', img: 'img/inquisitor/arcane_empowerment.png', url: 'https://grimdawn.fandom.com/wiki/Arcane_Empowerment_(Skill)'},
	'DeadlyAim': {title: 'Deadly Aim', img: 'img/inquisitor/deadly_aim.png', url: 'https://grimdawn.fandom.com/wiki/Deadly_Aim_(Skill)'},
	'RuneofKalastor': {title: 'Rune of Kalastor', img: 'img/inquisitor/rune_of_kalastor.png', url: 'https://grimdawn.fandom.com/wiki/Rune_of_Kalastor_(Skill)'},
	'Ignition': {title: 'Ignition', img: 'img/inquisitor/ignition.png', url: 'https://grimdawn.fandom.com/wiki/Ignition_(Skill)'},
	'ArtifactHandling': {title: 'Artifact Handling', img: 'img/inquisitor/artifact_handling.png', url: 'https://grimdawn.fandom.com/wiki/Artifact_Handling_(Skill)'},

	'ReapingStrike': {title: 'Reaping Strike', img: 'img/necromancer/reaping_strike.png', url: 'https://grimdawn.fandom.com/wiki/Reaping_Strike_(Skill)'},
	'NecroticEdge': {title: 'Necrotic Edge', img: 'img/necromancer/necrotic_edge.png', url: 'https://grimdawn.fandom.com/wiki/Necrotic_Edge_(Skill)'},
	'SiphonSouls': {title: 'Siphon Souls', img: 'img/necromancer/siphon_souls.png', url: 'https://grimdawn.fandom.com/wiki/Siphon_Souls_(Skill)'},
	'SearSouls': {title: 'Sear Souls', img: 'img/necromancer/sear_souls.png', url: 'https://grimdawn.fandom.com/wiki/Sear_Souls_(Skill)'},
	'BloodBoil': {title: 'Blood Boil', img: 'img/necromancer/blood_boil.png', url: 'https://grimdawn.fandom.com/wiki/Blood_Boil_(Skill)'},
	'DrainEssence': {title: 'Drain Essence', img: 'img/necromancer/drain_essence.png', url: 'https://grimdawn.fandom.com/wiki/Drain_Essence_(Skill)'},
	'Gravechill': {title: 'Gravechill', img: 'img/necromancer/gravechill.png', url: 'https://grimdawn.fandom.com/wiki/Gravechill_(Skill)'},
	'HungeringReach': {title: 'Hungering Reach', img: 'img/necromancer/hungering_reach.png', url: 'https://grimdawn.fandom.com/wiki/Hungering_Reach_(Skill)'},
	'Decomposition': {title: 'Decomposition', img: 'img/necromancer/decomposition.png', url: 'https://grimdawn.fandom.com/wiki/Decomposition_(Skill)'},
	'HarbingerofSouls': {title: 'Harbinger of Souls', img: 'img/necromancer/harbinger_of_souls.png', url: 'https://grimdawn.fandom.com/wiki/Harbinger_of_Souls_(Skill)'},
	'RavenousEarth': {title: 'Ravenous Earth', img: 'img/necromancer/ravenous_earth.png', url: 'https://grimdawn.fandom.com/wiki/Ravenous_Earth_(Skill)'},
	'Decay': {title: 'Decay', img: 'img/necromancer/decay.png', url: 'https://grimdawn.fandom.com/wiki/Decay_(Skill)'},
	'FoulEruption': {title: 'Foul Eruption', img: 'img/necromancer/foul_eruption.png', url: 'https://grimdawn.fandom.com/wiki/Foul_Eruption_(Skill)'},
	'BoneHarvest': {title: 'Bone Harvest', img: 'img/necromancer/bone_harvest.png', url: 'https://grimdawn.fandom.com/wiki/Bone_Harvest_(Skill)'},
	'HarvesterofDeath': {title: 'Harvester of Death', img: 'img/necromancer/harvester_of_death.png', url: 'https://grimdawn.fandom.com/wiki/Harvester_of_Death_(Skill)'},
	'Dread': {title: 'Dread', img: 'img/necromancer/dread.png', url: 'https://grimdawn.fandom.com/wiki/Dread_(Skill)'},
	'SoulHarvest': {title: 'Soul Harvest', img: 'img/necromancer/soul_harvest.png', url: 'https://grimdawn.fandom.com/wiki/Soul_Harvest_(Skill)'},
	'ReapSpirit': {title: 'Reap Spirit', img: 'img/necromancer/reap_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Reap_Spirit_(Skill)'},
	'RaiseSkeletons': {title: 'Raise Skeletons', img: 'img/necromancer/raise_skeletons.png', url: 'https://grimdawn.fandom.com/wiki/Raise_Skeletons_(Skill)'},
	'UndeadLegion': {title: 'Undead Legion', img: 'img/necromancer/undead_legion.png', url: 'https://grimdawn.fandom.com/wiki/Undead_Legion_(Skill)'},
	'WilloftheCrypt': {title: 'Will of the Crypt', img: 'img/necromancer/will_of_the_crypt.png', url: 'https://grimdawn.fandom.com/wiki/Will_of_the_Crypt_(Skill)'},
	'IllOmen': {title: 'Ill Omen', img: 'img/necromancer/ill_omen.png', url: 'https://grimdawn.fandom.com/wiki/Ill_Omen_(Skill)'},
	'SummonBlightFiend': {title: 'Summon Blight Fiend', img: 'img/necromancer/summon_blight_fiend.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Blight_Fiend_(Skill)'},
	'UnstableAnomaly': {title: 'Unstable Anomaly', img: 'img/necromancer/unstable_anomaly.png', url: 'https://grimdawn.fandom.com/wiki/Unstable_Anomaly_(Skill)'},
	'RottingFumes': {title: 'Rotting Fumes', img: 'img/necromancer/rotting_fumes.png', url: 'https://grimdawn.fandom.com/wiki/Rotting_Fumes_(Skill)'},
	'BlightBurst': {title: 'Blight Burst', img: 'img/necromancer/blight_burst.png', url: 'https://grimdawn.fandom.com/wiki/Blight_Burst_(Skill)'},
	'MasterofDeath': {title: 'Master of Death', img: 'img/necromancer/master_of_death.png', url: 'https://grimdawn.fandom.com/wiki/Master_of_Death_(Skill)'},
	'SpectralBinding': {title: 'Spectral Binding', img: 'img/necromancer/spectral_binding.png', url: 'https://grimdawn.fandom.com/wiki/Spectral_Binding_(Skill)'},
	'SpectralWrath': {title: 'Spectral Wrath', img: 'img/necromancer/spectral_wrath.png', url: 'https://grimdawn.fandom.com/wiki/Spectral_Wrath_(Skill)'},
	'CalloftheGrave': {title: 'Call of the Grave', img: 'img/necromancer/call_of_the_grave.png', url: 'https://grimdawn.fandom.com/wiki/Call_of_the_Grave_(Skill)'},
	'MarkofTorment': {title: 'Mark of Torment', img: 'img/necromancer/mark_of_torment.png', url: 'https://grimdawn.fandom.com/wiki/Mark_of_Torment_(Skill)'},
		
	'Safeguard': {title: 'Safeguard', img: 'img/oathkeeper/safeguard.png', url: 'https://grimdawn.fandom.com/wiki/Safeguard_(Skill)'},
	'Smite': {title: 'Smite', img: 'img/oathkeeper/smite.png', url: 'https://grimdawn.fandom.com/wiki/Smite_(Skill)'},
	'ShatteringSmash': {title: 'Shattering Smash', img: 'img/oathkeeper/shattering_smash.png', url: 'https://grimdawn.fandom.com/wiki/Shattering_Smash_(Skill)'},
	'EyeofReckoning': {title: 'Eye of Reckoning', img: 'img/oathkeeper/eye_of_reckoning.png', url: 'https://grimdawn.fandom.com/wiki/Eye_of_Reckoning_(Skill)'},
	'Soulfire': {title: 'Soulfire', img: 'img/oathkeeper/soulfire.png', url: 'https://grimdawn.fandom.com/wiki/Soulfire_(Skill)'},
	'ViresMight': {title: "Vire's Might", img: 'img/oathkeeper/vire_s_might.png', url: "https://grimdawn.fandom.com/wiki/Vire's_Might_(Skill)"},
	'VolcanicMight': {title: 'Volcanic Might', img: 'img/oathkeeper/volcanic_might.png', url: 'https://grimdawn.fandom.com/wiki/Volcanic_Might_(Skill)'},
	'VolcanicStride': {title: 'Volcanic Stride', img: 'img/oathkeeper/volcanic_stride.png', url: 'https://grimdawn.fandom.com/wiki/Volcanic_Stride_(Skill)'},
	'TectonicShift': {title: 'Tectonic Shift', img: 'img/oathkeeper/tectonic_shift.png', url: 'https://grimdawn.fandom.com/wiki/Tectonic_Shift_(Skill)'},
	'AegisofMenhir': {title: 'Aegis of Menhir', img: 'img/oathkeeper/aegis_of_menhir.png', url: 'https://grimdawn.fandom.com/wiki/Aegis_of_Menhir_(Skill)'},
	'AvengingShield': {title: 'Avenging Shield', img: 'img/oathkeeper/avenging_shield.png', url: 'https://grimdawn.fandom.com/wiki/Avenging_Shield_(Skill)'},
	'AegisofThorns': {title: 'Aegis of Thorns', img: 'img/oathkeeper/aegis_of_thorns.png', url: 'https://grimdawn.fandom.com/wiki/Aegis_of_Thorns_(Skill)'},
	'Reprisal': {title: 'Reprisal', img: 'img/oathkeeper/reprisal.png', url: 'https://grimdawn.fandom.com/wiki/Reprisal_(Skill)'},
	'SummonGuardianofEmpyrion': {title: 'Summon Guardian of Empyrion', img: 'img/oathkeeper/summon_guardian_of_empyrion.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Guardian_of_Empyrion_(Skill)'},
	'ScionofDreeg': {title: 'Scion of Dreeg', img: 'img/oathkeeper/scion_of_dreeg.png', url: 'https://grimdawn.fandom.com/wiki/Scion_of_Dreeg_(Skill)'},
	'CelestialPresence': {title: 'Celestial Presence', img: 'img/oathkeeper/celestial_presence.png', url: 'https://grimdawn.fandom.com/wiki/Celestial_Presence_(Skill)'},
	'Judgment': {title: 'Judgment', img: 'img/oathkeeper/judgment.png', url: 'https://grimdawn.fandom.com/wiki/Judgment_(Skill)'},
	'CrushingVerdict': {title: 'Crushing Verdict', img: 'img/oathkeeper/crushing_verdict.png', url: 'https://grimdawn.fandom.com/wiki/Crushing_Verdict_(Skill)'},
	'HeartofWrath': {title: 'Heart of Wrath', img: 'img/oathkeeper/heart_of_wrath.png', url: 'https://grimdawn.fandom.com/wiki/Heart_of_Wrath_(Skill)'},
	'DivineMandate': {title: 'Divine Mandate', img: 'img/oathkeeper/divine_mandate.png', url: 'https://grimdawn.fandom.com/wiki/Divine_Mandate_(Skill)'},
	'RighteousFervor': {title: 'Righteous Fervor', img: 'img/oathkeeper/righteous_fervor.png', url: 'https://grimdawn.fandom.com/wiki/Righteous_Fervor_(Skill)'},
	'DreegsReproach': {title: "Dreeg's Reproach", img: 'img/oathkeeper/transmuters.png', url: "https://grimdawn.fandom.com/wiki/Dreeg's_Reproach_(Skill)"},
	'Consecration': {title: 'Consecration', img: 'img/oathkeeper/consecration.png', url: 'https://grimdawn.fandom.com/wiki/Consecration_(Skill)'},
	'Retribution': {title: 'Retribution', img: 'img/oathkeeper/retribution.png', url: 'https://grimdawn.fandom.com/wiki/Retribution_(Skill)'},
	'PresenceofVirtue': {title: 'Presence of Virtue', img: 'img/oathkeeper/presence_of_virtue.png', url: 'https://grimdawn.fandom.com/wiki/Presence_of_Virtue_(Skill)'},
	'Haven': {title: 'Haven', img: 'img/oathkeeper/haven.png', url: 'https://grimdawn.fandom.com/wiki/Haven_(Skill)'},
	'Rebuke': {title: 'Rebuke', img: 'img/oathkeeper/rebuke.png', url: 'https://grimdawn.fandom.com/wiki/Rebuke_(Skill)'},
	'PathoftheThree': {title: 'Path of the Three', img: 'img/oathkeeper/path_of_the_three.png', url: 'https://grimdawn.fandom.com/wiki/Path_of_the_Three_(Skill)'},
	'Resilience': {title: 'Resilience', img: 'img/oathkeeper/resilience.png', url: 'https://grimdawn.fandom.com/wiki/Resilience_(Skill)'},
	'Ascension': {title: 'Ascension', img: 'img/oathkeeper/ascension.png', url: 'https://grimdawn.fandom.com/wiki/Ascension_(Skill)'},
	'ClarityofPurpose': {title: 'Clarity of Purpose', img: 'img/oathkeeper/clarity_of_purpose.png', url: 'https://grimdawn.fandom.com/wiki/Clarity_of_Purpose_(Skill)'},
};

window.baseUrl = window.baseUrl||'';
var skillTriggerList = [].slice.call(document.querySelectorAll('skill'));
skillTriggerList.map(function(skillTriggerEl) {
	var skillKey = skillTriggerEl.innerHTML.replace(/[^A-Za-z0-9]/g, '');
	var newItem = document.createElement('b');
	if (skillList.hasOwnProperty(skillKey)) {
		var skill = skillList[skillKey];
		newItem.innerHTML = '<a href="' + skill.url + '"><img src="' + window.baseUrl + skill.img + '" alt="' + skill.title + '" title="' + skill.title + '" /></a>';
	} else {
		newItem.innerHTML = 'Unknown skill ' + skillKey;
	}
	skillTriggerEl.parentNode.replaceChild(newItem, skillTriggerEl);
});