var skillList = {
	'RangedExpertise': {title: 'Ranged Expertise', img: 'img/inquisitor/ranged_expertise.png', url: 'https://grimdawn.fandom.com/wiki/Ranged_Expertise_(Skill)'},
	'BurstingRound': {title: 'Bursting Round', img: 'img/inquisitor/bursting_round.png', url: 'https://grimdawn.fandom.com/wiki/Bursting_Round_(Skill)'},
	'WordofRenewal': {title: 'Word of Renewal', img: 'img/inquisitor/word_of_renewal.png', url: 'https://grimdawn.fandom.com/wiki/Word_of_Renewal_(Skill)'},
	'DeadlyAim': {title: 'Deadly Aim', img: 'img/inquisitor/deadly_aim.png', url: 'https://grimdawn.fandom.com/wiki/Deadly_Aim_(Skill)'},
	'ChillingRounds': {title: 'Chilling Rounds', img: 'img/inquisitor/chilling_rounds.png', url: 'https://grimdawn.fandom.com/wiki/Chilling_Rounds_(Skill)'},
	'InquisitorSeal': {title: 'Inquisitor Seal', img: 'img/inquisitor/inquisitor_seal.png', url: 'https://grimdawn.fandom.com/wiki/Inquisitor_Seal_(Skill)'},
	'StormSpread': {title: 'Storm Spread', img: 'img/inquisitor/storm_spread.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Spread_(Skill)'},
	'ArcaneEmpowerment': {title: 'Arcane Empowerment', img: 'img/inquisitor/arcane_empowerment.png', url: 'https://grimdawn.fandom.com/wiki/Arcane_Empowerment_(Skill)'},
	'NullField': {title: 'Null Field', img: 'img/inquisitor/null_field.png', url: 'https://grimdawn.fandom.com/wiki/Null_Field_(Skill)'},
	'SteelResolve': {title: 'Steel Resolve', img: 'img/inquisitor/steel_resolve.png', url: 'https://grimdawn.fandom.com/wiki/Steel_Resolve_(Skill)'},
	'RuneofKalistor': {title: 'Rune of Kalastor', img: 'img/inquisitor/rune_of_kalastor.png', url: 'https://grimdawn.fandom.com/wiki/Rune_of_Kalastor_(Skill)'},
	'Vigor': {title: 'Vigor', img: 'img/inquisitor/vigor.png', url: 'https://grimdawn.fandom.com/wiki/Vigor_(Skill)'},
	'Ignition': {title: 'Ignition', img: 'img/inquisitor/ignition.png', url: 'https://grimdawn.fandom.com/wiki/Ignition_(Skill)'},
	'AuraofCenture': {title: 'Aura of Censure', img: 'img/inquisitor/aura_of_censure.png', url: 'https://grimdawn.fandom.com/wiki/Aura_of_Censure_(Skill)'},
	'StormBoxofElgoloth': {title: 'Storm Box of Elgoloth', img: 'img/inquisitor/storm_box_of_elgoloth.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Box_of_Elgoloth_(Skill)'},
	'RuneofHagarrad': {title: 'Rune of Hagarrad', img: 'img/inquisitor/rune_of_hagarrad.png', url: 'https://grimdawn.fandom.com/wiki/Rune_of_Hagarrad_(Skill)'},
	'BitingCold': {title: 'Biting Cold', img: 'img/inquisitor/biting_cold.png', url: 'https://grimdawn.fandom.com/wiki/Biting_Cold_(Skill)'},
	'LightningTether': {title: 'Lightning Tether', img: 'img/inquisitor/lightning_tether.png', url: 'https://grimdawn.fandom.com/wiki/Lightning_Tether_(Skill)'},
	'Chillsurge': {title: 'Chillsurge', img: 'img/inquisitor/chillsurge.png', url: 'https://grimdawn.fandom.com/wiki/Chillsurge_(Skill)'},
	'ArtifactHandling': {title: 'Artifact Handling', img: 'img/inquisitor/artifact_handling.png', url: 'https://grimdawn.fandom.com/wiki/Artifact_Handling_(Skill)'},
	'AuraofCensure': {title: 'Aura of Censure', img: 'img/inquisitor/aura_of_censure.png', url: 'https://grimdawn.fandom.com/wiki/Aura_of_Censure_(Skill)'},

	'MarkoviansAdvantage': {title: 'Markovian’s Advantage', img: 'img/soldier/markovian_s_advantage.png', url: "https://grimdawn.fandom.com/wiki/Markovian's_Advantage_(Skill)"},
	'FieldCommand': {title: 'Field Command', img: 'img/soldier/field_command.png', url: 'https://grimdawn.fandom.com/wiki/Field_Command_(Skill)'},	
	'OleronsRage': {title: 'Oleron’s Rage', img: 'img/soldier/oleron_s_rage.png', url: "https://grimdawn.fandom.com/wiki/Oleron's_Rage_(Skill)"},
	'Cadence': {title: 'Cadence', img: 'img/soldier/cadence.png', url: 'https://grimdawn.fandom.com/wiki/Cadence_(Skill)'},
	'FightingSpirit': {title: 'Fighting Spirit', img: 'img/soldier/fighting_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Fighting_Spirit_(Skill)'},
	'FightingForm': {title: 'Fighting Form', img: 'img/soldier/fighting_form.png', url: 'https://grimdawn.fandom.com/wiki/Fighting_Form_(Skill)'},
	'WarCry': {title: 'War Cry', img: 'img/soldier/war_cry.png', url: 'https://grimdawn.fandom.com/wiki/War_Cry_(Skill)'},
	'DecoratedSoldier': {title: 'Decorated Soldier', img: 'img/soldier/decorated_soldier.png', url: 'https://grimdawn.fandom.com/wiki/Decorated_Soldier_(Skill)'},
	'SquadTactics': {title: 'Squad Tactics', img: 'img/soldier/squad_tactics.png', url: 'https://grimdawn.fandom.com/wiki/Squad_Tactics_(Skill)'},
	'BreakMorale': {title: 'Break Morale', img: 'img/soldier/break_morale.png', url: 'https://grimdawn.fandom.com/wiki/Break_Morale_(Skill)'},
	'ScarsofBattle': {title: 'Scars of Battle', img: 'img/soldier/scars_of_battle.png', url: 'https://grimdawn.fandom.com/wiki/Scars_of_Battle_(Skill)'},
	'DeadlyMomentum': {title: 'Deadly Momentum', img: 'img/soldier/deadly_momentum.png', url: 'https://grimdawn.fandom.com/wiki/Deadly_Momentum_(Skill)'},

	'FireStrike': {title: 'Fire Strike', img: 'img/demolitionist/fire_strike.png', url: 'https://grimdawn.fandom.com/wiki/Fire_Strike_(Skill)'},
	'FlameTouched': {title: 'Flame Touched', img: 'img/demolitionist/flame_touched.png', url: 'https://grimdawn.fandom.com/wiki/Flame_Touched_(Skill)'},
	'BlackwaterCocktail': {title: 'Blackwater Cocktail', img: 'img/demolitionist/blackwater_cocktail.png', url: 'https://grimdawn.fandom.com/wiki/Blackwater_Cocktail_(Skill)'},
	'ExplosiveStrike': {title: 'Explosive Strike', img: 'img/demolitionist/explosive_strike.png', url: 'https://grimdawn.fandom.com/wiki/Explosive_Strike_(Skill)'},
	'HighPotency': {title: 'High Potency', img: 'img/demolitionist/high_potency.png', url: 'https://grimdawn.fandom.com/wiki/High_Potency_(Skill)'},
	'VindictiveFlame': {title: 'Vindictive Flame', img: 'img/demolitionist/vindictive_flame.png', url: 'https://grimdawn.fandom.com/wiki/Vindictive_Flame_(Skill)'},
	'SearingMight': {title: 'Searing Might', img: 'img/demolitionist/searing_might.png', url: 'https://grimdawn.fandom.com/wiki/Searing_Might_(Skill)'},
	'Grenado': {title: 'Grenado', img: 'img/demolitionist/grenado.png', url: 'https://grimdawn.fandom.com/wiki/Grenado_(Skill)'},
	'DemonFire': {title: 'Demon Fire', img: 'img/demolitionist/demon_fire.png', url: 'https://grimdawn.fandom.com/wiki/Demon_Fire_(Skill)'},
	'UlzuinsWrath': {title: "Ulzuin's Wrath", img: 'img/demolitionist/ulzuin_s_wrath.png', url: "https://grimdawn.fandom.com/wiki/Ulzuin's_Wrath_(Skill)"},
	'AgonizingFlames': {title: 'Agonizing Flames', img: 'img/demolitionist/agonizing_flames.png', url: 'https://grimdawn.fandom.com/wiki/Agonizing_Flames_(Skill)'},
	'ThermiteMine': {title: 'Thermite Mine', img: 'img/demolitionist/thermite_mine.png', url: 'https://grimdawn.fandom.com/wiki/Thermite_Mine_(Skill)'},
	'BlastShield': {title: 'Blast Shield', img: 'img/demolitionist/blast_shield.png', url: 'https://grimdawn.fandom.com/wiki/Blast_Shield_(Skill)'},
	'Flashbang': {title: 'Flashbang', img: 'img/demolitionist/flashbang.png', url: 'https://grimdawn.fandom.com/wiki/Flashbang_(Skill)'},
	'SearingLight': {title: 'Searing Light', img: 'img/demolitionist/searing_light.png', url: 'https://grimdawn.fandom.com/wiki/Searing_Light_(Skill)'},
	'Temper': {title: 'Temper', img: 'img/demolitionist/temper.png', url: 'https://grimdawn.fandom.com/wiki/Temper_(Skill)'},
	'StaticStrike': {title: 'Static Strike', img: 'img/demolitionist/static_strike.png', url: 'https://grimdawn.fandom.com/wiki/Static_Strike_(Skill)'},
	'Brimstone': {title: 'Brimstone', img: 'img/demolitionist/brimstone.png', url: 'https://grimdawn.fandom.com/wiki/Brimstone_(Skill)'},
	'CanisterBomb': {title: 'Canister Bomb', img: 'img/demolitionist/canister_bomb.png', url: 'https://grimdawn.fandom.com/wiki/Canister_Bomb_(Skill)'},
	
	'BruteForce': {title: 'Brute Force', img: 'img/shaman/brute_force.png', url: 'https://grimdawn.fandom.com/wiki/Brute_Force_(Skill)'},
	'DevouringSwarm': {title: 'Devouring Swarm', img: 'img/shaman/devouring_swarm.png', url: 'https://grimdawn.fandom.com/wiki/Devouring_Swarm_(Skill)'},
	'MogdrogensPact': {title: 'Mogdrogen’s Pact', img: 'img/shaman/mogdrogen_s_pact.png', url: "https://grimdawn.fandom.com/wiki/Mogdrogen's_Pact_(Skill)"},
	'GraspingVines': {title: 'Grasping Vines', img: 'img/shaman/grasping_vines.png', url: 'https://grimdawn.fandom.com/wiki/Grasping_Vines_(Skill)'},
	'HeartoftheWild': {title: 'Heart of the Wild', img: 'img/shaman/heart_of_the_wild.png', url: 'https://grimdawn.fandom.com/wiki/Heart_of_the_Wild_(Skill)'},
	'OakSkin': {title: 'Oak Skin', img: 'img/shaman/oak_skin.png', url: 'https://grimdawn.fandom.com/wiki/Oak_Skin_(Skill)'},
	'EntanglingVines': {title: 'Entangling Vines', img: 'img/shaman/entangling_vines.png', url: 'https://grimdawn.fandom.com/wiki/Entangling_Vines_(Skill)'},
	'WendigoTotem': {title: 'Wendigo Totem', img: 'img/shaman/wendigo_totem.png', url: 'https://grimdawn.fandom.com/wiki/Wendigo_Totem_(Skill)'},
	'StormTotem': {title: 'Storm Totem ', img: 'img/shaman/storm_totem.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Totem_(Skill)'},
	'CorruptedStorm': {title: 'Corrupted Storm', img: 'img/shaman/corrupted_storm.png', url: 'https://grimdawn.fandom.com/wiki/Corrupted_Storm_(Skill)'},
	'BloodPact': {title: 'Blood Pact', img: 'img/shaman/blood_pact.png', url: 'https://grimdawn.fandom.com/wiki/Blood_Pact_(Skill)'},
	'Savagery': {title: 'Savagery', img: 'img/shaman/savagery.png', url: 'https://grimdawn.fandom.com/wiki/Savagery_(Skill)'},
	'MightoftheBear': {title: 'Might of the Bear', img: 'img/shaman/might_of_the_bear.png', url: 'https://grimdawn.fandom.com/wiki/Might_of_the_Bear_(Skill)'},
	'FeralHunger': {title: 'Feral Hunger', img: 'img/shaman/feral_hunger.png', url: 'https://grimdawn.fandom.com/wiki/Feral_Hunger_(Skill)'},
	'TenacityoftheBoar': {title: 'Tenacity of the Boar', img: 'img/shaman/tenacity_of_the_boar.png', url: 'https://grimdawn.fandom.com/wiki/Tenacity_of_the_Boar_(Skill)'},
	'StormTouched': {title: 'Storm Touched', img: 'img/shaman/storm_touched.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Touched_(Skill)'},
	'SummonBriarthorn': {title: 'Summon Briarthorn', img: 'img/shaman/summon_briarthorn.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Briarthorn_(Skill)'},
	'GroundSlam': {title: 'Ground Slam', img: 'img/shaman/ground_slam.png', url: 'https://grimdawn.fandom.com/wiki/Ground_Slam_(Skill)'},
	'EmboldeningPresence': {title: 'Emboldening Presence', img: 'img/shaman/emboldening_presence.png', url: 'https://grimdawn.fandom.com/wiki/Emboldening_Presence_(Skill)'},
	'ConjurePrimalSpirit': {title: 'Conjure Primal Spirit', img: 'img/shaman/conjure_primal_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Conjure_Primal_Spirit_(Skill)'},
	'PrimalBond': {title: 'Primal Bond', img: 'img/shaman/primal_bond.png', url: 'https://grimdawn.fandom.com/wiki/Primal_Bond_(Skill)'},
	'WindDevil': {title: 'Wind Devil', img: 'img/shaman/wind_devil.png', url: 'https://grimdawn.fandom.com/wiki/Wind_Devil_(Skill)'},
	'RagingTempest': {title: 'Raging Tempest', img: 'img/shaman/raging_tempest.png', url: 'https://grimdawn.fandom.com/wiki/Raging_Tempest_(Skill)'},
	'Maelstrom': {title: 'Maelstrom', img: 'img/shaman/maelstrom.png', url: 'https://grimdawn.fandom.com/wiki/Maelstrom_(Skill)'},
	
	'CurseofFrailty': {title: 'Curse of Frailty', img: 'img/occultist/curse_of_frailty.png', url: 'https://grimdawn.fandom.com/wiki/Curse_of_Frailty_(Skill)'},
	'BloodyPox': {title: 'Bloody Pox', img: 'img/occultist/bloody_pox.png', url: 'https://grimdawn.fandom.com/wiki/Bloody_Pox_(Skill)'},
	'SolaelsWitchfire': {title: 'Solael’s Witchfire', img: 'img/occultist/solael_s_witchfire.png', url: "https://grimdawn.fandom.com/wiki/Solael's_Witchfire_(Skill)"},
	'Vulnerability': {title: 'Vulnerability', img: 'img/occultist/vulnerability.png', url: 'https://grimdawn.fandom.com/wiki/Vulnerability_(Skill)'},
	'BloodofDreeg': {title: 'Blood of Dreeg', img: 'img/occultist/blood_of_dreeg.png', url: 'https://grimdawn.fandom.com/wiki/Blood_of_Dreeg_(Skill)'},
	'Wasting': {title: 'Wasting', img: 'img/occultist/wasting.png', url: 'https://grimdawn.fandom.com/wiki/Wasting_(Skill)'},
	'SecondRite': {title: 'Second Rite', img: 'img/occultist/second_rite.png', url: 'https://grimdawn.fandom.com/wiki/Second_Rite_(Skill)'},
	'AspectoftheGuardian': {title: 'Aspect of Guardian', img: 'img/occultist/aspect_of_guardian.png', url: 'https://grimdawn.fandom.com/wiki/Aspect_of_the_Guardian_(Skill)'},
	'Possession': {title: 'Possession', img: 'img/occultist/possession.png', url: 'https://grimdawn.fandom.com/wiki/Possession_(Skill)'},
	'Manipulation': {title: 'Manipulation', img: 'img/occultist/manipulation.png', url: 'https://grimdawn.fandom.com/wiki/Manipulation_(Skill)'},
	'SummonFamiliar': {title: 'Summon Familiar', img: 'img/occultist/summon_familiar.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Familiar_(Skill)'},
	'SummonHellhound': {title: 'Summon Hellhound', img: 'img/occultist/summon_hellhound.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Hellhound_(Skill)'},
	'StormSpirit': {title: 'Storm Spirit', img: 'img/occultist/storm_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Storm_Spirit_(Skill)'},
	'Hellfire': {title: 'Hellfire', img: 'img/occultist/hellfire.png', url: 'https://grimdawn.fandom.com/wiki/Hellfire_(Skill)'},
	'BondsofBysmiel': {title: 'Bonds of Bysmiel', img: 'img/occultist/bonds_of_bysmiel.png', url: 'https://grimdawn.fandom.com/wiki/Bonds_of_Bysmiel_(Skill)'},
	'DoomBolt': {title: 'Doom Bolt', img: 'img/occultist/doom_bolt.png', url: 'https://grimdawn.fandom.com/wiki/Doom_Bolt_(Skill)'},
	'DreegsEvilEye': {title: "Dreeg's Evil Eye", img: 'img/occultist/dreeg_s_evil_eye.png', url: "https://grimdawn.fandom.com/wiki/Dreeg's_Evil_Eye_(Skill)"},
	'BloodBurst': {titile: 'Blood Burst', img: 'img/occultist/blood_burst.png', url: 'https://grimdawn.fandom.com/wiki/Blood_Burst_(Skill)'},
	'FocusedGaze': {title: 'Focused Gaze', img: 'img/occultist/focused_gaze.png', url: 'https://grimdawn.fandom.com/wiki/Focused_Gaze_(Skill)'},
	
	'RaiseSkeletons': {title: 'Raise Skeletons', img: 'img/necromancer/raise_skeletons.png', url: 'https://grimdawn.fandom.com/wiki/Raise_Skeletons_(Skill)'},
	'SpectralBinding': {title: 'Spectral Binding', img: 'img/necromancer/spectral_binding.png', url: 'https://grimdawn.fandom.com/wiki/Spectral_Binding_(Skill)'},
	'UndeadLegion': {title: 'Undead Legion', img: 'img/necromancer/undead_legion.png', url: 'https://grimdawn.fandom.com/wiki/Undead_Legion_(Skill)'},
	'SummonBlightFiend': {title: 'Summon Blight Fiend', img: 'img/necromancer/summon_blight_fiend.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Blight_Fiend_(Skill)'},
	'SpectralWrath': {title: 'Spectral Wrath', img: 'img/necromancer/spectral_wrath.png', url: 'https://grimdawn.fandom.com/wiki/Spectral_Wrath_(Skill)'},
	'WilloftheCrypt': {title: 'Will of the Crypt', img: 'img/necromancer/will_of_the_crypt.png', url: 'https://grimdawn.fandom.com/wiki/Will_of_the_Crypt_(Skill)'},
	'RottingFumes': {title: 'Rotting Fumes', img: 'img/necromancer/rotting_fumes.png', url: 'https://grimdawn.fandom.com/wiki/Rotting_Fumes_(Skill)'},
	'CalloftheGrave': {title: 'Call of the Grave', img: 'img/necromancer/call_of_the_grave.png', url: 'https://grimdawn.fandom.com/wiki/Call_of_the_Grave_(Skill)'},
	'BlightBurst': {title: 'Blight Burst', img: 'img/necromancer/blight_burst.png', url: 'https://grimdawn.fandom.com/wiki/Blight_Burst_(Skill)'},
	'MasterofDeath': {title: 'Master of Death', img: 'img/necromancer/master_of_death.png', url: 'https://grimdawn.fandom.com/wiki/Master_of_Death_(Skill)'},
	
	'DualBlades': {title: 'Dual Blades', img: 'img/nightblade/dual_blades.png', url: 'https://grimdawn.fandom.com/wiki/Dual_Blades_(Skill)'},
	'AmarastasBladeBurst': {title: "Amarasta's Blade Burst", img: 'img/nightblade/amarasta_s_blade_burst.png', url: "https://grimdawn.fandom.com/wiki/Amarasta's_Blade_Burst_(Skill)"},
	'VeilofShadow': {title: 'Veil of Shadow', img: 'img/nightblade/veil_of_shadow.png', url: 'https://grimdawn.fandom.com/wiki/Veil_of_Shadow_(Skill)'},
	'BelgothiansShears': {title: "Belgothian's Shears", img: 'img/nightblade/belgothian_s_shears.png', url: "https://grimdawn.fandom.com/wiki/Belgothian's_Shears_(Skill)"},
	'PneumaticBurst': {title: 'Pneumatic Burst', img: 'img/nightblade/pneumatic_burst.png', url: 'https://grimdawn.fandom.com/wiki/Pneumatic_Burst_(Skill)'},
	'NidallasHiddenHand': {title: "Nidalla's Hidden Hand", img: 'img/nightblade/nidalla_s_hidden_hand.png', url: "https://grimdawn.fandom.com/wiki/Nidalla's_Hidden_Hand_(Skill)"},
	'ShadowStrike': {title: 'Shadow Strike', img: 'img/nightblade/shadow_strike.png', url: 'https://grimdawn.fandom.com/wiki/Shadow_Strike_(Skill)'},
	'PhantasmalArmor': {title: 'Phantasmal Armor', img: 'img/nightblade/phantasmal_armor.png', url: 'https://grimdawn.fandom.com/wiki/Phantasmal_Armor_(Skill)'},
	'AmarastasQuickCut': {title: "Amarasta's Quick Cut", img: 'img/nightblade/amarasta_s_quick_cut.png', url: "https://grimdawn.fandom.com/wiki/Amarasta's_Quick_Cut_(Skill)"},
	'LethalAssault': {title: 'Lethal Assault', img: 'img/nightblade/lethal_assault.png', url: 'https://grimdawn.fandom.com/wiki/Lethal_Assault_(Skill)'},
	'ShadowDance': {title: 'Shadow Dance', img: 'img/nightblade/shadow_dance.png', url: 'https://grimdawn.fandom.com/wiki/Shadow_Dance_(Skill)'},
	'NightsChill': {title: "Night's Chill", img: 'img/nightblade/night_s_chill.png', url: "https://grimdawn.fandom.com/wiki/Night's_Chill_(Skill)"},
	'RingofSteel': {title: 'Ring of Steel', img: 'img/nightblade/ring_of_steel.png', url: 'https://grimdawn.fandom.com/wiki/Ring_of_Steel_(Skill)'},
	'AnatomyofMurder': {title: 'Anatomy of Murder', img: 'img/nightblade/anatomy_of_murder.png', url: 'https://grimdawn.fandom.com/wiki/Anatomy_of_Murder_(Skill)'},
	'NidallasJustifiableEnds': {title: "Nidalla's Justifiable Ends", img: 'img/nightblade/nidalla_s_justifiable_ends.png', url: "https://grimdawn.fandom.com/wiki/Nidalla's_Justifiable_Ends_(Skill)"},
	'WhirlingDeath': {title: 'Whirling Death', img: 'img/nightblade/whirling_death.png', url: 'https://grimdawn.fandom.com/wiki/Whirling_Death_(Skill)'},
	'ElementalAwakening': {title: 'Elemental Awakening', img: 'img/nightblade/elemental_awakening.png', url: 'https://grimdawn.fandom.com/wiki/Elemental_Awakening_(Skill)'},
	'MercilessRepertoire': {title: 'Merciless Repertoire', img: 'img/nightblade/merciless_repertoire.png', url: 'https://grimdawn.fandom.com/wiki/Merciless_Repertoire_(Skill)'},
	'Execution': {title: 'Execution', img: 'img/nightblade/execution.png', url: 'https://grimdawn.fandom.com/wiki/Execution_(Skill)'},
	'BladeSpirit': {title: 'Blade Spirit', img: 'img/nightblade/blade_spirit.png', url: 'https://grimdawn.fandom.com/wiki/Blade_Spirit_(Skill)'},
	'BreathofBelgothian': {title: 'Breath of Belgothian', img: 'img/nightblade/breath_of_belgothian.png', url: 'https://grimdawn.fandom.com/wiki/Breath_of_Belgothian_(Skill)'},
	'RingofFrost': {title: 'Ring of Frost', img: 'img/nightblade/ring_of_frost.png', url: 'https://grimdawn.fandom.com/wiki/Ring_of_Frost_(Skill)'},
	'CircleofSlaughter': {title: 'Circle of Slaughter', img: 'img/nightblade/circle_of_slaughter.png', url: 'https://grimdawn.fandom.com/wiki/Circle_of_Slaughter_(Skill)'},
	'Nighfall': {title: 'Nighfall', img: 'img/nightblade/nightfall.png', url: 'https://grimdawn.fandom.com/wiki/Nightfall_(Skill)'},
	
	'RighteousFervor': {title: 'Righteous Fervor', img: 'img/oathkeeper/righteous_fervor.png', url: 'https://grimdawn.fandom.com/wiki/Righteous_Fervor_(Skill)'},
	'DreegsReproach': {title: "Dreeg's Reproach", img: 'img/oathkeeper/transmuters.png', url: "https://grimdawn.fandom.com/wiki/Dreeg's_Reproach_(Skill)"},
	'PresenceofVirtue': {title: 'Presence of Virtue', img: 'img/oathkeeper/presence_of_virtue.png', url: 'https://grimdawn.fandom.com/wiki/Presence_of_Virtue_(Skill)'},
	'Resilience': {title: 'Resilience', img: 'img/oathkeeper/resilience.png', url: 'https://grimdawn.fandom.com/wiki/Resilience_(Skill)'},
	'Consecration': {title: 'Consecration', img: 'img/oathkeeper/consecration.png', url: 'https://grimdawn.fandom.com/wiki/Consecration_(Skill)'},
	'Haven': {title: 'Haven', img: 'img/oathkeeper/haven.png', url: 'https://grimdawn.fandom.com/wiki/Haven_(Skill)'},
	'Ascension': {title: 'Ascension', img: 'img/oathkeeper/ascension.png', url: 'https://grimdawn.fandom.com/wiki/Ascension_(Skill)'},
	'Rebuke': {title: 'Rebuke', img: 'img/oathkeeper/rebuke.png', url: 'https://grimdawn.fandom.com/wiki/Rebuke_(Skill)'},
	'ClarityofPurpose': {title: 'Clarity of Purpose', img: 'img/oathkeeper/clarity_of_purpose.png', url: 'https://grimdawn.fandom.com/wiki/Clarity_of_Purpose_(Skill)'},
	'SummonGuardianofEmpyrion': {title: 'Summon Guardian of Empyrion', img: 'img/oathkeeper/summon_guardian_of_empyrion.png', url: 'https://grimdawn.fandom.com/wiki/Summon_Guardian_of_Empyrion_(Skill)'},
	'Retribution': {title: 'Retribution', img: 'img/oathkeeper/retribution.png', url: 'https://grimdawn.fandom.com/wiki/Retribution_(Skill)'},
	'ScionofDreeg': {title: 'Scion of Dreeg', img: 'img/oathkeeper/scion_of_dreeg.png', url: 'https://grimdawn.fandom.com/wiki/Scion_of_Dreeg_(Skill)'},
	'CelestialPresence': {title: 'Celestial Presence', img: 'img/oathkeeper/celestial_presence.png', url: 'https://grimdawn.fandom.com/wiki/Celestial_Presence_(Skill)'},
	'PathoftheThree': {title: 'Path of the Three', img: 'img/oathkeeper/path_of_the_three.png', url: 'https://grimdawn.fandom.com/wiki/Path_of_the_Three_(Skill)'},
};

var skillTriggerList = [].slice.call(document.querySelectorAll('skill'));
var skillList = skillTriggerList.map(function(skillTriggerEl) {
	var skillKey = skillTriggerEl.innerHTML.replace(/[^A-Za-z0-9]/g, '');
	var newItem = document.createElement('b');
	if (skillList.hasOwnProperty(skillKey)) {
		var skill = skillList[skillKey];
		newItem.innerHTML = '<a href="' + skill.url + '"><img src="' + skill.img + '" alt="' + skill.title + '" title="' + skill.title + '" /></a>';
	} else {
		newItem.innerHTML = 'Unknown skill ' + skillKey;
	}
	skillTriggerEl.parentNode.replaceChild(newItem, skillTriggerEl);
});